export const setores = [
  "ASMETO (Associação dos Magistrados do Tocantins)",
  "Assessoria Militar",
  "ASTJ (Associação dos Servidores do Tribunal de Justiça)",
  "Comissão de Jurisprudencia e Documentação",
  "Comissão de Seleção e Treinamento",
  "Comissão Permanente de Acessibilidade e Inclusão",
  "Conselho da Magistratura",
  "Coordenadoria de Gestão Estratégica, Estatística e Projetos",
  "Coordenadoria Estadual da Mulher em Situação de Violência Doméstica e Familiar",
  "Corregedoria-Geral de Justiça",
  "Diretoria Administrativa",
  "Diretoria Controladoria Interna",
  "Diretoria de Gestão de Pessoas",
  "Diretoria de Infraestrutura e Obras",
  "Diretoria de Tecnologia de Informação",
  "Diretoria do Centro de Comunicação Social",
  "Diretoria Financeira",
  "Diretoria Geral",
  "Diretoria Judiciária",
  "Divisão de Contrainteligência do NIS",
  "Divisão de Serviços Gerais do Tribunal de Justiça",
  "Escola Superior da Magistratura Tocantinense",
  "Espaço Saúde",
  "Gabinete da Presidência",
  "Gabinete Des. Adolfo Amaro Mendes",
  "Gabinete Des. Eurípedes Lamounier",
  "Gabinete Des. Helvécio de Brito Maia Neto",
  "Gabinete Des. João Rigo Guimarães",
  "Gabinete Des. Marco Villas Boas",
  "Gabinete Des. Pedro Nelson de Miranda Coutinho",
  "Gabinete Desa. Ângela Issa Haonat",
  "Gabinete Desa. Ângela M. Ribeiro Prudente",
  "Gabinete Desa. Etelvina Maria Sampaio Felipe",
  "Gabinete Desa. Jacqueline Adorno de La Cruz Barbosa",
  "Gabinete Desa. Maysa Vendramini Rosal",
  "Gabinete Juiz Convocado Jocy Gomes de Almeida",
  "Junta Médica",
  "Justiça Militar",
  "Justiça Móvel",
  "Lanchonete",
  "Núcleo de Apoio as Comarcas",
  "Núcleo Permanente de Métodos Consensuais de Solução de Conflitos",
  "OAB",
  "Ouvidoria Judiciária",
  "Serviço Social",
]
